### ISSUE TITLE
支不支持逆向，json到可视化表单

### ISSUE THREAD

**Issue by zhangchao6018** [zyqwst/json-schema-editor-vue#11]
目前我尝试将json-schema-editor-vue跑了个demo
发现目前支持编辑表单生成json
1.想问下能否支持从json逆向到可视化表单
2.有二次开发的需求，但是技术上不太懂vue，想将生成的json保存起来存到数据库
3.目前json-schema-editor-vue 演示看起来有点问题，跟你提供的demo有一些出入：左侧不支持json显示，格式排版有些问题，不直到咋调...

![image](https://user-images.githubusercontent.com/44044963/105438963-f5998800-5c9e-11eb-98ba-81b16ebbdc25.png)

**Comment by zyqwst** [comment]
第一个问题，json-schema-ediitor-vue是帮助开发人员生成json schema数据，左侧的json是用户传入的参数，所以你可以按需设置是否可编辑，编辑后会自动更新右侧的表单；
![image](https://user-images.githubusercontent.com/10893736/105440007-d56ac880-5ca0-11eb-8cae-9345c16a5ec8.png)

你这个样式看起来是正常的，左侧的json数据没有显示出来是因为你左侧没有提供数据组件展示json数据。可查看example/App.vue
![image](https://user-images.githubusercontent.com/10893736/105440147-0c40de80-5ca1-11eb-86fe-5517bfa5b001.png)

**Comment by zhangchao6018** [comment]
> 第一个问题，json-schema-ediitor-vue是帮助开发人员生成json schema数据，左侧的json是用户传入的参数，所以你可以按需设置是否可编辑，编辑后会自动更新右侧的表单；
> ![image](https://user-images.githubusercontent.com/10893736/105440007-d56ac880-5ca0-11eb-8cae-9345c16a5ec8.png)
> 
> 你这个样式看起来是正常的，左侧的json数据没有显示出来是因为你左侧没有提供数据组件展示json数据。可查看example/App.vue
> ![image](https://user-images.githubusercontent.com/10893736/105440147-0c40de80-5ca1-11eb-86fe-5517bfa5b001.png)

demo项目能否提供，我这边不会调样式，害..

**Comment by zyqwst** [comment]
就这个文件，其实使用很简单
![image](https://user-images.githubusercontent.com/10893736/105444096-2fbb5780-5ca8-11eb-8f95-263742fbdbdb.png)

**Comment by zhangchao6018** [comment]
> 就这个文件，其实使用很简单
> ![image](https://user-images.githubusercontent.com/10893736/105444096-2fbb5780-5ca8-11eb-8f95-263742fbdbdb.png)

好的 我先研究下 谢谢

**Comment by zhangchao6018** [comment]
> > 就这个文件，其实使用很简单
> > ![image](https://user-images.githubusercontent.com/10893736/105444096-2fbb5780-5ca8-11eb-8f95-263742fbdbdb.png)
> 
> 好的 我先研究下 谢谢

求助  请问如何开启json文件生成表单的功能

**Comment by zyqwst** [comment]
> > > 就这个文件，其实使用很简单
> > > ![image](https://user-images.githubusercontent.com/10893736/105444096-2fbb5780-5ca8-11eb-8f95-263742fbdbdb.png)
> > 
> > 
> > 好的 我先研究下 谢谢
> 
> 求助 请问如何开启json文件生成表单的功能

无语，你直接修改json数据会自动生成表单呀

**Comment by zhangchao6018** [comment]
> > > > 就这个文件，其实使用很简单
> > > > ![image](https://user-images.githubusercontent.com/10893736/105444096-2fbb5780-5ca8-11eb-8f95-263742fbdbdb.png)
> > > 
> > > 
> > > 好的 我先研究下 谢谢
> > 
> > 
> > 求助 请问如何开启json文件生成表单的功能
> 
> 无语，你直接修改json数据会自动生成表单呀

....但是不可编辑啊.....
