### ISSUE TITLE
遇到了一个频繁报错：[Vue warn]: Failed to resolve directive: ant-portal

### ISSUE THREAD

**Issue by joisun** [zyqwst/json-schema-editor-vue#13]
似乎是当 Modal 弹出的时候都会触发这个报错

我的本地开发环境没有装antvue

**Comment by zyqwst** [comment]
这个ant-design-vue的问题，按需引入会出现这个现象，但是不影响使用。https://github.com/vueComponent/ant-design-vue/issues/2394

**Comment by joisun** [comment]
> 这个ant-design-vue的问题，按需引入会出现这个现象，但是不影响使用。[vueComponent/ant-design-vue#2394](https://github.com/vueComponent/ant-design-vue/issues/2394)

好的好的
