### ISSUE TITLE
建议加上允许字段为null的复选框

### ISSUE THREAD

**Issue by YiuTerran** [zyqwst/json-schema-editor-vue#15]
RT，这个很常用

**Comment by zyqwst** [comment]
json schema规范通过是否必须来控制
![image](https://user-images.githubusercontent.com/10893736/127807034-c768109a-b5ba-462b-bb1f-d44ff34309cc.png)

**Comment by YiuTerran** [comment]
@zyqwst 是否必须对应js里面的undefined，和允许为null不是一个意思。

一个字段设置成非必须，但是如果不允许type为null，validate的时候还是会失败。

**Comment by zyqwst** [comment]
不选不就是允许为null吗？

**Comment by YiuTerran** [comment]
@zyqwst 不选表示可以没有这个字段，为null要求额外加一个类型，比如`type:["string", "null"]`

可以参考这个：https://stackoverflow.com/questions/16241333/specify-a-value-can-be-a-string-or-null-with-json-schema
