### ISSUE TITLE
请问可以支持enum属性编辑吗

### ISSUE THREAD

**Issue by edisonyan** [zyqwst/json-schema-editor-vue#18]
比如
`{
  "root": {
    "description": "",
    "required": [
      "CustomerCode"
    ],
    "type": "object",
    "properties": {
      "CustomerCode": {
        "description": "code",
        "type": "string"
      },
      "TypeItem": {
        "description": "type",
        "uniqueItems": false,
        "type": "array",
        "items": {
          "format": "int32",
          "enum": [
            1,
            2,
            3,
            4
          ],**
          "type": "integer"
        }
      }
    }
  }
}`
目前通过自定义属性也无法添加enum

**Comment by zyqwst** [comment]
目前json-schema-editor-vue不支持枚举，本周我抽空加下。或者你也可以加下提个PR，string/number/integer三种类型加下枚举属性

**Comment by zyqwst** [comment]
已在npm发布2.0.2版本，支持enum编辑
![image](https://user-images.githubusercontent.com/10893736/163702928-66d96768-c601-420e-9056-e77a80f85e9a.png)
