### ISSUE TITLE
不是标准的json  schema语句

### ISSUE THREAD

**Issue by wang3690004** [zyqwst/json-schema-editor-vue#19]
请教一下  例子中的 根节点 "root"  是必须要填写的吗？ 例子中 不是标准的json schema语句？

**Comment by zyqwst** [comment]
非必须，只是给编辑器一个默认的json-schema对象，编辑器编辑的内容也是此对象。你完全可以写成这样：

```
<template>
  <div id="app">
    <div class="title">
      Demo
    </div>
    <div class="container">
      <pre>{{tree}}</pre>
      <json-schema-editor class="schema" :disabled="false" :value="tree"/>
    </div>
  </div>
</template>

<script>
export default {
  name: 'App',
  data() {
    return {
      tree:
      {
        other: {
          type: "array"
        }
      }
    }
  }
}
</script>
```

<img width="1351" alt="image" src="https://user-images.githubusercontent.com/10893736/164351976-d6b1d04c-a755-4f83-886d-6d6a5c7ae7df.png">

**Comment by wang3690004** [comment]
那好像是不支持标准的json schema 语句  
比如 输入 
 {
  "title": "GameConfig",
  "description": "游戏配置",
  "type": "object",
  "properties": {
    "foo": {
      "type": "string"
    }
  }
}  
解析不出来

**Comment by zyqwst** [comment]
你这个数据怎么传递给value呢？外面再包一层
```
 <json-schema-editor class="schema" :disabled="false" :value="tree"/>
```

**Comment by wang3690004** [comment]
感觉是不是可以把现有的递归组件拆分出来  在他们之前再加一个专门用来处理root 根节点的情况  ？类似这样 
< json-schema>
  < json-schema-root />  处理根节点
  < json-schema-objcet> 遍历根节点的 properties
  < json-schema-item /> string number  boolean 等类型
  < /json-schema-object>
< json-schema-array>
< /json-schema>
