### ISSUE TITLE
如何vue3中使用

### ISSUE THREAD

**Issue by bbcvc** [zyqwst/json-schema-editor-vue#21]
我想在vue3中使用这个库，但是得到了这个错误
![image](https://user-images.githubusercontent.com/52622877/172990926-72c583e1-c734-4ae2-a0a8-f1f3a47721b6.png)

**Comment by zyqwst** [comment]
抱歉，json-schema-editor-vue不支持vue3，vue3版本在规划了

**Comment by zyqwst** [comment]
Vue3版本已发布到npm，安装使用
```
npm install json-schema-editor-vue3
```
