### ISSUE TITLE
请问可以帮忙支持下Vue3吗？

### ISSUE THREAD

**Issue by eacdy** [zyqwst/json-schema-editor-vue#22]
请问可以帮忙支持下Vue3吗？

**Comment by zyqwst** [comment]
大家对vue3的呼声很高，近期会抽空出vue3的版本

**Comment by eacdy** [comment]
万分感谢！期待ing！

**Comment by zyqwst** [comment]
Vue3版本已发布到npm，安装使用
```
npm install json-schema-editor-vue3
```

**Comment by eacdy** [comment]
超高效！万分感谢！貌似GitHub地址没有开源哦https://github.com/zyqwst/-json-schema-editor-vue3

访问是404

**Comment by zyqwst** [comment]
https://github.com/zyqwst/json-schema-editor-vue3
