### ISSUE TITLE
点击设置

### ISSUE THREAD

**Issue by 571470351** [zyqwst/json-schema-editor-vue#23]
![image](https://user-images.githubusercontent.com/71878730/179889533-1002279e-7507-487d-9a5f-05142e0ecca1.png)
不知道为什么会出现这个情况，如果作者有空的话！可以帮忙解答一下吗

**Comment by zyqwst** [comment]
抱歉，请描述清楚你的使用方式，我未发现此问题。

**Comment by 571470351** [comment]
> 抱歉，请描述清楚你发现的使用方式，我未解决此问题。
就是我直接在项目中导入该组件，点击这个按钮就出现报错
![image](https://user-images.githubusercontent.com/71878730/179955780-d7208bfd-55dc-43bc-9502-57744b84b7c9.png)

**Comment by zyqwst** [comment]
> > 抱歉，请描述清楚你发现的使用方式，我未解决此问题。
> > 就是我直接在项目中导入该组件，点击这个按钮就出现报错
> > ![image](https://user-images.githubusercontent.com/71878730/179955780-d7208bfd-55dc-43bc-9502-57744b84b7c9.png)

你使用vue几？然后有没有使用ant design vue?

**Comment by 571470351** [comment]
> > > 抱歉，请描述清楚你发现的使用方法，我没有解决这个问题。
> > > 就是我直接在项目中导入该组件，点击这个按钮就报错
> > > ![图片](https://user-images.githubusercontent.com/71878730/179955780-d7208bfd-55dc-43bc-9502-57744b84b7c9.png)
> 
> 你使用vue几？然后有没有使用ant design vue？

vue2.6.1 有使用ant 1.7.8
![image](https://user-images.githubusercontent.com/71878730/179958372-06c5bad8-6679-48f5-8273-cb80e23ddf9d.png)

**Comment by zyqwst** [comment]
点击设置弹窗有没有正常出来？

**Comment by zyqwst** [comment]
> 点击设置弹窗有没有正常出来？



> > > > 抱歉，请描述清楚你发现的使用方法，我没有解决这个问题。
> > > > 就是我直接在项目中导入该组件，点击这个按钮就报错
> > > > ![图片](https://user-images.githubusercontent.com/71878730/179955780-d7208bfd-55dc-43bc-9502-57744b84b7c9.png)
> > 
> > 
> > 你使用vue几？然后有没有使用ant design vue？
> 
> vue2.6.1 有使用ant 1.7.8 ![image](https://user-images.githubusercontent.com/71878730/179958372-06c5bad8-6679-48f5-8273-cb80e23ddf9d.png)

点击设置弹窗有没有正常出来？

**Comment by 571470351** [comment]
> > 点击设置弹窗有没有正常出来？
> 
> > > > > 抱歉，请描述清楚你发现的使用方法，我没有解决这个问题。
> > > > > 就是我直接在项目中导入该组件，点击这个按钮就报错
> > > > > ![图片](https://user-images.githubusercontent.com/71878730/179955780-d7208bfd-55dc-43bc-9502-57744b84b7c9.png)
> > > 
> > > 
> > > 你使用vue几？然后有没有使用ant design vue？
> > 
> > 
> > vue2.6.1 有使用ant 1.7.8 ![image](https://user-images.githubusercontent.com/71878730/179958372-06c5bad8-6679-48f5-8273-cb80e23ddf9d.png)
> 
> 点击设置弹窗有没有正常出来？

是的，没有正常出来

**Comment by zyqwst** [comment]
经测试，是vue版本与ant-design-vue兼容性问题，请升级vue@2.7.8。

**Comment by 571470351** [comment]
> 经测试，是vue版本与ant-design-vue兼容性问题，请升级vue@2.7.8。

谢谢您！
