### ISSUE TITLE
关于“$ref”解析

### ISSUE THREAD

**Issue by Colin000000** [zyqwst/json-schema-editor-vue#24]
外部导入json schema时，不能解析“$ref”。目前项目中有这种场景，请问作者有解决方案吗？如果有空的话麻烦解答下，谢谢！

**Comment by zyqwst** [comment]
> 外部导入json schema时，不能解析“$ref”。目前项目中有这种场景，请问作者有解决方案吗？如果有空的话麻烦解答下，谢谢！

麻烦贴一下你的json-schema数据

**Comment by Colin000000** [comment]
![image](https://user-images.githubusercontent.com/74804847/180596625-9839894d-4a01-46b7-8265-522ddea17178.png)

**Comment by zyqwst** [comment]
抱歉，不支持json内部引用
