### ISSUE TITLE
安装vue2 下拉框点击有问题  点击后 不消失

### ISSUE THREAD

**Issue by wwg2017** [zyqwst/json-schema-editor-vue#25]
下拉框点击后不消失啊
![image](https://user-images.githubusercontent.com/27998578/184792151-d3bb92ee-f34b-4b30-9480-bc291d7f33d0.png)

**Comment by zyqwst** [comment]
升级vue@2.7.8试试看。近期遇到的ant-design-vue的报错基本上都是版本问题
