### ISSUE TITLE
添加自定义属性页面重复显示

### ISSUE THREAD

**Issue by lc5910** [zyqwst/json-schema-editor-vue#27]
如图，官方列子：设置一个自定义属性field保存后关闭窗口，再次点击设置进入，多了一个同样的field属性，再重复同样的操作都会多出同样的自定义属性。
同时还有另外一个问题，关闭窗口后再打开设置，删除自定义属性删除无效。
![WeChat Screenshot_20220824111332](https://user-images.githubusercontent.com/21080465/186329227-ea5c145b-5879-40fe-8aab-773fe0f07804.png)

**Comment by zyqwst** [comment]
感谢，抽空修复

**Comment by zyqwst** [comment]
2.1.0已修复此问题
