### ISSUE TITLE
引入json-schema-editor-vue.css后出现Module build failed: BrowserslistError: Unknown browser query `dead`

### ISSUE THREAD

**Issue by caixunshi** [zyqwst/json-schema-editor-vue#28]
如题，网上找了各种版本，都解决不了这个问题

**Comment by zyqwst** [comment]
请把package截图看看

**Comment by caixunshi** [comment]
{
  "name": "myvue",
  "version": "1.0.0",
  "description": "A Vue.js project",
  "author": "shi.cai",
  "private": true,
  "scripts": {
    "dev": "webpack-dev-server --inline --progress --config build/webpack.dev.conf.js",
    "start": "npm run dev",
    "build": "node build/build.js"
  },
  "dependencies": {
    "browserslist": "^4.21.3",
    "json-schema-editor-vue": "^2.0.4",
    "vue": "^2.7.8"
  },
  "devDependencies": {
    "autoprefixer": "^7.1.2",
    "babel-core": "^6.22.1",
    "babel-helper-vue-jsx-merge-props": "^2.0.3",
    "babel-loader": "^7.1.1",
    "babel-plugin-syntax-jsx": "^6.18.0",
    "babel-plugin-transform-runtime": "^6.22.0",
    "babel-plugin-transform-vue-jsx": "^3.5.0",
    "babel-preset-env": "^1.3.2",
    "babel-preset-stage-2": "^6.22.0",
    "chalk": "^2.0.1",
    "copy-webpack-plugin": "^4.0.1",
    "css-loader": "^1.0.0",
    "extract-text-webpack-plugin": "^3.0.0",
    "file-loader": "^1.1.4",
    "friendly-errors-webpack-plugin": "^1.6.1",
    "html-webpack-plugin": "^2.30.1",
    "node-notifier": "^5.1.2",
    "optimize-css-assets-webpack-plugin": "^3.2.0",
    "ora": "^1.2.0",
    "portfinder": "^1.0.13",
    "postcss-import": "^11.0.0",
    "postcss-loader": "^2.0.8",
    "postcss-url": "^7.2.1",
    "rimraf": "^2.6.0",
    "semver": "^5.3.0",
    "shelljs": "^0.7.6",
    "uglifyjs-webpack-plugin": "^1.1.1",
    "url-loader": "^0.5.8",
    "vue-loader": "^13.3.0",
    "vue-style-loader": "^3.0.1",
    "vue-template-compiler": "^2.5.2",
    "webpack": "^3.6.0",
    "webpack-bundle-analyzer": "^2.9.0",
    "webpack-dev-server": "^2.9.1",
    "webpack-merge": "^4.1.0"
  },
  "engines": {
    "node": ">= 6.0.0",
    "npm": ">= 3.0.0"
  }
}

**Comment by caixunshi** [comment]
我用vue-cli生成的脚手架项目引入也会报同样的错误，实在找不到原因，所以自己基于element-ui的el-tree组件写了一个json-schema的编辑组件

**Comment by zyqwst** [comment]
#31
