### ISSUE TITLE
样式问题

### ISSUE THREAD

**Issue by wwg2017** [zyqwst/json-schema-editor-vue#30]
json稍微多就不行了，我看yapi可以支持很多

![image](https://user-images.githubusercontent.com/27998578/187408064-fed97d23-9b3f-4149-b73e-f3520a522ec3.png)

**Comment by zyqwst** [comment]
看了其他yapi版本，层级一多都会有问题，2种解决思路：
1.如果json层级比较多，可以使编辑器宽度全屏；
2.控制json层级；
![image](https://user-images.githubusercontent.com/10893736/189862355-4fd7225e-dae8-49e9-9d67-c380bac834e2.png)
