### ISSUE TITLE
element-admin-template项目，直接npm install后无法使用

### ISSUE THREAD

**Issue by lishuncoder** [zyqwst/json-schema-editor-vue#31]
环境：
@vue/cli 4.4.1
node 16.17
npm 8.15

{
  "name": "vue-admin-template",
  "version": "4.4.0",
  "description": "A vue admin template with Element UI & axios & iconfont & permission control & lint",
  "author": "Pan <panfree23@gmail.com>",
  "scripts": {
    "local": "vue-cli-service serve --mode local",
    "dev": "vue-cli-service serve",
    "build:prod": "vue-cli-service build",
    "build:dev": "vue-cli-service build --mode development",
    "build:stage": "vue-cli-service build --mode staging",
    "preview": "node build/index.js --preview",
    "svgo": "svgo -f src/icons/svg --config=src/icons/svgo.yml",
    "lint": "eslint --ext .js,.vue src",
    "test:unit": "jest --clearCache && vue-cli-service test:unit",
    "test:ci": "npm run lint && npm run test:unit"
  },
  "dependencies": {
    "axios": "0.18.1",
    "clipboard": "^2.0.11",
    "core-js": "3.6.5",
    "echarts": "4.2.1",
    "element-ui": "2.13.2",
    "js-cookie": "2.2.0",
    "normalize.css": "7.0.0",
    "nprogress": "0.2.0",
    "path-to-regexp": "2.4.0",
    "qs": "^6.10.3",
    "vue": "2.6.10",
    "vue-count-to": "^1.0.13",
    "vue-router": "3.0.6",
    "vuex": "3.1.0"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "4.4.4",
    "@vue/cli-plugin-eslint": "4.4.4",
    "@vue/cli-plugin-unit-jest": "4.4.4",
    "@vue/cli-service": "4.4.4",
    "@vue/test-utils": "1.0.0-beta.29",
    "autoprefixer": "9.5.1",
    "babel-eslint": "10.1.0",
    "babel-jest": "23.6.0",
    "babel-plugin-dynamic-import-node": "2.3.3",
    "chalk": "2.4.2",
    "connect": "3.6.6",
    "eslint": "6.7.2",
    "eslint-plugin-vue": "6.2.2",
    "html-webpack-plugin": "3.2.0",
    "json-schema-editor-vue": "^2.0.4",
    "mockjs": "1.0.1-beta3",
    "runjs": "4.3.2",
    "sass": "1.26.8",
    "sass-loader": "8.0.2",
    "script-ext-html-webpack-plugin": "2.1.3",
    "serve-static": "1.13.2",
    "svg-sprite-loader": "4.1.3",
    "svgo": "1.2.2",
    "vue-template-compiler": "2.6.10"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions"
  ],
  "engines": {
    "node": ">=8.9",
    "npm": ">= 3.0.0"
  },
  "license": "MIT"
}

**Comment by lishuncoder** [comment]
![image](https://user-images.githubusercontent.com/35674916/189916543-428a3087-17d8-48bb-ad6c-fa04db56bfb2.png)

**Comment by lishuncoder** [comment]
![image](https://user-images.githubusercontent.com/35674916/189916616-b579d782-7f4b-4e46-9c88-7452c0a3dc45.png)

**Comment by lishuncoder** [comment]
如果在main.js中
import JsonSchemaEditor from 'json-schema-editor-vue'
import 'json-schema-editor-vue/lib/json-schema-editor-vue.css'
Vue.use(JsonSchemaEditor)

之后同样也是不能使用，想请教下是什么问题？
是因为我vue版本问题吗？
还是node npm 版本问题？

![image](https://user-images.githubusercontent.com/35674916/189919721-2d1ce89f-4ac5-4684-ae08-13f776921f4b.png)

**Comment by zyqwst** [comment]
本地新建项目测试无问题，请检查其他配置
![image](https://user-images.githubusercontent.com/10893736/190390283-35e1370c-8543-49a1-8245-fbbdc9adf684.png)
![image](https://user-images.githubusercontent.com/10893736/190390434-7a599d55-399b-4ae0-9fcf-eacd7082d07e.png)

**Comment by iamyb** [comment]
@zyqwst 遇到同样的问题，在项目[element-ui-admin](https://github.com/PanJiaChen/vue-element-admin) 模板里面使用的时候会出现。
