### ISSUE TITLE
参数多了情况输入文本框很卡  一秒一个字

### ISSUE THREAD

**Issue by wwg2017** [zyqwst/json-schema-editor-vue#32]
参数多了情况输入文本框很卡  一秒一个字，急救为啥 ，客户不满意

**Comment by zyqwst** [comment]
我这边场景json结构不是很复杂，能否提供下你的json-schema ，我看下。

**Comment by wwg2017** [comment]
不用 发 你直接输入多点的json就可以了
{
&nbsp;&nbsp;&nbsp; "statutyus": 1,
&nbsp;&nbsp;&nbsp; "messatyuge": "ok",
&nbsp;&nbsp;&nbsp; "dattyutyua": {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "liverewrId": 4,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "titlrwete": "33",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "begrteinDate": "2022-10-21 00:00:00",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "endertDate": null,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "kindert": 34,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "hoserttUserId": 4,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "gueertestName": null,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "coveryeImageUrl": "8",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "thumtertbnails": null,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "desceyeription": "",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "creatyeryeeDate": null,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "stayerytus": 0,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "liverteeStatus": null,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "uniqteyueId": null,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "dureryeation": null,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "onlietrtneCount": null,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "totalVttertisit": null,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "totalFteravour": null,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "opeertratorId": null,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "shoyerterwDm": null,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "opeteratorUserName": null,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "totteralComment": null,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "m3uytr8Url": null,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "mp4erterUrl": null,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "mp4ytryUrlJobId": null,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "selferterUrl": null,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "deviceSource": 0,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "netSouytrrceUrl": "",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "netSoutertrceType": "",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "selfPlayCount": null,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "partetenerPlayCount": null,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "taertgs": [],
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "partertnerId": null,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "scheytrma": null,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "clasyrerttsName": null,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "headetertrtVideo": null,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "netSouerterceConfigId": null,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "netSouytryrceAearId": 0,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "netSourceIspId": 0,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "noSignytralTime": null,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "liveTetype": 6,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "screertenType": 1,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "barrageClose": null,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "regioertnId": 0,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "cityeyetId": 0,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "deaertelerId": null,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "souyrtyrce": 0,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "cheerteckState": null,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "linktyteryMobile": "",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "dealtyrtererUrl": "",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "weCetehat": null,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "dunNteoticeCount": null,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "dunWaeterrningCount": null,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "dunNoytrSignalCount": null,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "audiertetNotice": null,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "audiyrtytWarning": null,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "audiertyrtNoSignal": null,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "audirtyrttorId": null,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "auditorName": null,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "isFullyrScreen": null,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "hostrtyName": "",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "kinrtydTag": null,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "wertyrtchatLink": "4",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "usyrterId": 3,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "icyrtyp": "",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "wechatText": "",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "dertyalerImg": "",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "deayrtylerLink": "",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "branrtydIdAndSerialIdVoList": [],
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "liveTags": null,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "lvGueuytstVoList": [],
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "motoryrtcycleVoList": [],
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "liveTtyuagList": [
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "iertd": 0,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "liteveId": ,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "tagyrtId": ,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "tagretyName": "",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "creartyteTime": "2022-10-20T11:56:04.288",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "updartyteTime": "2022-10-20T11:56:04.288"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; }
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ],
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "thumbUpIrtyrtconList": []
&nbsp;&nbsp;&nbsp; },
&nbsp;&nbsp;&nbsp; "errtycd": null,
&nbsp;&nbsp;&nbsp; "succutyess": true
}





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zyqwst/json-schema-editor-vue"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月20日(星期四) 中午1:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zyqwst/json-schema-editor-vue] 参数多了情况输入文本框很卡  一秒一个字 (Issue #32)





 
我这边场景json结构不是很复杂，能否提供下你的json-schema ，我看下。

**Comment by zyqwst** [comment]
建议客户换电脑吧，我试了下不卡顿😝

**Comment by wwg2017** [comment]
> 建议客户换电脑吧，我试了下不卡顿😝

不可能哦 你输入很多字段，，然后 去编辑备注，，输入一个字符就要等待1s

**Comment by zyqwst** [comment]
原因我大概知道。晚上我发布个版本，修改事件监测为blur

**Comment by wwg2017** [comment]
> 原因我大概知道。晚上我发布个版本，修改事件监测为blur

我需要更新下项目重新下载下吗

**Comment by zyqwst** [comment]
> 

是的，你应该是vue2吧？json-schema升级到2.1.1版本即可

**Comment by wwg2017** [comment]
> > 
> 
> 是的，你应该是vue2吧？json-schema升级到2.1.1版本即可

是的   是直接升级 packge里面版本 吗，，还是要手动安装下，，我用的nuxt.js里面既有vue2  又有vue3的语法，，但是你这个功能我用的是vue2

**Comment by wwg2017** [comment]
> > 
> 
> 是的，你应该是vue2吧？json-schema升级到2.1.1版本即可
您好 您升级了吗 ，我升级到2.1.1还是很卡
