### ISSUE TITLE
vue3版本编辑器删除问题

### ISSUE THREAD

**Issue by bernie0308** [zyqwst/json-schema-editor-vue#33]
作者你好，我想请问vue3版本，不论删除对象的哪一条，都是最后一个值被删除，请问这个有解决方案吗

**Comment by zyqwst** [comment]
请截图展示下你遇到的问题

**Comment by bernie0308** [comment]
![image](https://user-images.githubusercontent.com/35795306/196942977-2034a76e-6313-4edb-8907-8d6ce8ea142d.png)
![image](https://user-images.githubusercontent.com/35795306/196943943-272bcbca-7cb8-4232-b8de-a5128cecea5b.png)
截图在这里，我把 vue3版本的demo下载下来运行。发现也有这个小问题

**Comment by bernie0308** [comment]
而且左侧的json数据和 编辑里内的数据无法一一对应。请问作者大大这个问题怎么解决呢

**Comment by bernie0308** [comment]
![image](https://user-images.githubusercontent.com/35795306/196958887-f4f95ad6-2976-4f7f-9bc6-df359563d06b.png)
你好，我找到原因了，其实删除成功了，只是key值没有做双向绑定的更新，具体原因是绑定了default-value而不是v-model:value

**Comment by zyqwst** [comment]
已修复，感谢

**Comment by zyqwst** [comment]
已修复，感谢
