### ISSUE TITLE
修改已存在的数据，顺序会乱掉，这个怎么解决？

### ISSUE THREAD

**Issue by go1nggo** [zyqwst/json-schema-editor-vue#36]
<img width="1155" alt="image" src="https://user-images.githubusercontent.com/38337102/198540326-77ce7cf2-173b-4eb3-b5a3-7ad924f0c2fe.png">
<img width="1220" alt="image" src="https://user-images.githubusercontent.com/38337102/198540521-1fcd0102-8ce9-458e-ab92-b7346547bc9f.png">

**Comment by zyqwst** [comment]
这个是由于json object的天生设计导致的，以非数字开头的属性新增或者修改会排到最后面。这个问题我在想办法修复

**Comment by zyqwst** [comment]
json-schema-editor-vue@2.2.0已修复此问题，请下载尝试

**Comment by go1nggo** [comment]
感谢大佬，之前我也有通过遍历修改key去解决
