### ISSUE TITLE
confirmAddCustomNode方法中变量写错了

### ISSUE THREAD

**Issue by OraJae** [zyqwst/json-schema-editor-vue#37]
文件：packages\json-schema-editor\main.vue 中 confirmAddCustomNode方法 中变量写错了，应该是 if (item.key === p.key)
![image](https://user-images.githubusercontent.com/49579359/199177989-508dabb9-db09-40f1-bb89-4c94a8f7c56b.png)

**Comment by yanluohao** [comment]
上面列的情况+1，不然会导致自定义属性只能新增一个，然后就报null下面不能读取key的错误；演示站点上的版本跟现在最新版本有版本差异

**Comment by zyqwst** [comment]
感谢！此问题在2.1.2版本修复
