### ISSUE TITLE
json-schema-editor修复

### ISSUE THREAD

**Issue by wwg2017** [zyqwst/json-schema-editor-vue#38]

**Comment by wwg2017** [comment]
每一次修改完数据，然后点击空白处，结果都会跑到最后怎么办。，怎么让顺序不变啊，或者加一个可选参数

**Comment by zyqwst** [comment]
这个issue之前也有人提过，我抽空处理下

**Comment by wwg2017** [comment]
> 这个issue之前也有人提过，我抽空处理下

多谢多谢哈，还有能加个上调下调的按钮吗 可以灵活控制参数顺序

**Comment by zyqwst** [comment]
> > 这个issue之前也有人提过，我抽空处理下
> 
> 多谢多谢哈，还有能加个上调下调的按钮吗 可以灵活控制参数顺序

只能界面上把自动排序控制下，实际是没办法的，json对象内部会字典序

**Comment by wwg2017** [comment]
> > > 这个issue之前也有人提过，我抽空处理下
> > 
> > 
> > 多谢多谢哈，还有能加个上调下调的按钮吗 可以灵活控制参数顺序
> 
> 只能界面上把自动排序控制下，实际是没办法的，json对象内部会字典序

对啊对啊 就是加个按钮 自己手动控制 啊 上调下调 ，如果那样就太牛逼 太完美了

**Comment by wwg2017** [comment]
> > > > 这个issue之前也有人提过，我抽空处理下
> > > 
> > > 
> > > 多谢多谢哈，还有能加个上调下调的按钮吗 可以灵活控制参数顺序
> > 
> > 
> > 只能界面上把自动排序控制下，实际是没办法的，json对象内部会字典序
> 
> 对啊对啊 就是加个按钮 自己手动控制 啊 上调下调 ，如果那样就太牛逼 太完美了

大神 有计划搞吗

**Comment by wwg2017** [comment]
> 这个issue之前也有人提过，我抽空处理下
这个可以处理吗

**Comment by zyqwst** [comment]
json-schema-editor-vue@2.2.0已修复此问题，请下载尝试
