### ISSUE TITLE
参数类型的选择可以支持自由拓展嘛！

### ISSUE THREAD

**Issue by lovimo** [zyqwst/json-schema-editor-vue#39]
现在的number、string、array...可以支持大部分场景
现在我想将这一套配置转换成真实的表单，如果可以定义一些更加精确的类型，配置起来就更为方便
比如下拉框，我想加一个selected类型，多选框加一个checkbox类型，单选框加一个radio类型... 然后每个类型里面的高级配置也可以自定义，这样的拓展性可以满足嘛大佬～

不增加类型，只是单纯的支持自定义高级配置里面的基础配置也是可以滴

**Comment by zyqwst** [comment]
这是json-schema的编辑器，遵守json-schema规范的，你这种场景要自己拉代码去扩展了
![image](https://user-images.githubusercontent.com/10893736/208064019-a88d313f-5681-42d1-bdd0-950185b49c58.png)
