### ISSUE TITLE
antv 1.6.3 加载 组件 有问题

### ISSUE THREAD

**Issue by pljay** [zyqwst/json-schema-editor-vue#4]
name字段 无法修改

**Comment by zyqwst** [comment]
请说明你使用的json-schema-editor-vue版本，以及详细描述错误信息

**Comment by pljay** [comment]
"json-schema-editor-vue": "^1.1.3"

**Comment by pljay** [comment]
"json-schema-editor-vue": "^1.1.3" 
![image](https://user-images.githubusercontent.com/35439240/90349480-976fd580-e06c-11ea-888d-be68c5e0043e.png)

**Comment by zyqwst** [comment]
> "json-schema-editor-vue": "^1.1.3"
> ![image](https://user-images.githubusercontent.com/35439240/90349480-976fd580-e06c-11ea-888d-be68c5e0043e.png)

抱歉，antd1.6.3和json-schema-editor-vue1.1.3 本地测试未发现此问题，是否可以提供问题源码？

**Comment by pljay** [comment]
<template>
  <a-card>
    <div id="JsonSchema">
      <div class="title">
        JsonSchema
      </div>
      <div class="container">
        <pre>{{tree}}</pre>
        <json-schema-editor class="schema" :value="tree" disabledType/>
      </div>
    </div>
  </a-card>
</template>

<script>
  export default {
    name: 'JsonSchema',
    data() {
      return {
        tree:
          {
            "root": {
              "type": "object",
            }
          }
      }
    }
  }
</script>
<style >
  *{
    padding:0;
    margin:0;
    box-sizing: border-box;
  }
  .title{
    text-align: center;
    font-size: 40px;
    font-weight: bold;
    height:100px;
    line-height: 100px;
  }
  .container{
    display: flex;
    padding:20px;
    width:80vw;
    min-width:800px;
    justify-content:center;
    height: calc(100vh - 150px);
    margin:auto;
  }
  .container>pre {
    font-family: monospace;
    height: 100%;
    overflow-y: auto;
    border:1px solid rgba(0,0,0,.1);
    border-radius: 8px;
    padding: 12px;
    width:50%
  }
  .schema{
    margin-left: 20px;
    width:50%;
    height: 100%;
    overflow-y: auto;
    overflow-x:hidden;
    border:1px solid rgba(0,0,0,.1);
    border-radius: 8px;
    padding: 12px;
  }
</style>

**Comment by pljay** [comment]
[JsonSchema.txt](https://github.com/zyqwst/json-schema-editor-vue/files/5100155/JsonSchema.txt)

**Comment by zyqwst** [comment]
> [JsonSchema.txt](https://github.com/zyqwst/json-schema-editor-vue/files/5100155/JsonSchema.txt)
请检查代码，未复现你说的问题。
请查看[代码片段](https://codesandbox.io/s/cool-waterfall-vp8dl)
