### ISSUE TITLE
单独改动源码重新发布到npm安装不生效

### ISSUE THREAD

**Issue by wwg2017** [zyqwst/json-schema-editor-vue#40]
单独改动源码重新发布到npm安装不生效，
改动这里的代码，从新发布到npm官网 再安装，还是不生效，走的还是原来的功能
![image](https://user-images.githubusercontent.com/27998578/208625740-6cadb885-ed70-449e-854f-8399a7a72593.png)

**Comment by zyqwst** [comment]
这个不应该呀，你发布的npm 包和版本号发出来看看

**Comment by wwg2017** [comment]
> 这个不应该呀，你发布的npm 包和版本号发出来看看

哦哦可以了，，不过还是想用你的那个能支持加个按钮调换编辑框的顺序吗 和  固定编辑框

**Comment by zyqwst** [comment]
> > 这个不应该呀，你发布的npm 包和版本号发出来看看
> 
> 哦哦可以了，，不过还是想用你的那个能支持加个按钮调换编辑框的顺序吗 和 固定编辑框

保持顺序的需求预计今天能处理好，按钮调整顺序这个需求对于我这个组件是不需要的

**Comment by wwg2017** [comment]
> > > 这个不应该呀，你发布的npm 包和版本号发出来看看
> > 
> > 
> > 哦哦可以了，，不过还是想用你的那个能支持加个按钮调换编辑框的顺序吗 和 固定编辑框
> 
> 保持顺序的需求预计今天能处理好，按钮调整顺序这个需求对于我这个组件是不需要的

能扩展加个参数么。我传递那个参数，然后就可以展示出这个功能，

**Comment by zyqwst** [comment]
json-schema-editor-vue@2.2.0已修复此问题，请下载尝试

**Comment by wwg2017** [comment]
> json-schema-editor-vue@2.2.0已修复此问题，请下载尝试
好的
