### ISSUE TITLE
输入title点击空白处消失

### ISSUE THREAD

**Issue by wwg2017** [zyqwst/json-schema-editor-vue#43]
![image](https://user-images.githubusercontent.com/27998578/211282425-487ca2d5-6e5c-47d4-b610-e76a73c7be90.png)
输入title后左边好像没有及时显示,, import json完数据之后再点击title
应该是2.1.1版本就不行了
  <a-input v-model="pickValue.title" class="ant-col-title" :placeholder="local['title']"/>
          <a-input :value="pickValue.title" class="ant-col-title" :placeholder="local['title']" @blur="e => pickValue.title=e.target.value"/>
好像是这么写法影响到了

**Comment by zyqwst** [comment]
用blur事件是考虑到json过大时操作会卡顿、不流畅

**Comment by wwg2017** [comment]
> 用blur事件是考虑到json过大时操作会卡顿、不流畅

嗯嗯，明白，但是备注编辑不上 麻烦大神搞下

**Comment by zyqwst** [comment]
> 

用最新的试试看2.2.0版本
http://json-schema.sviip.com/

**Comment by wwg2017** [comment]
> > 
> 
> 用最新的试试看2.2.0版本 http://json-schema.sviip.com/

![image](https://user-images.githubusercontent.com/27998578/211707587-e2affcbc-a198-4858-a772-487168876fcd.png)
不行啊，就是我说的问题啊，通过import导入进来的 再去编辑备注是没有的，，你可以试试

**Comment by zyqwst** [comment]
> > > 
> > 
> > 
> > 用最新的试试看2.2.0版本 http://json-schema.sviip.com/
> 
> ![image](https://user-images.githubusercontent.com/27998578/211707587-e2affcbc-a198-4858-a772-487168876fcd.png) 不行啊，就是我说的问题啊，通过import导入进来的 再去编辑备注是没有的，，你可以试试

2.2.1已修复此问题
![image](https://user-images.githubusercontent.com/10893736/211710242-b70e639b-d38e-44e7-b501-e50bba0a5659.png)

**Comment by wwg2017** [comment]
膜拜大神
