### ISSUE TITLE
json字段后面有个空格特殊字符，导入的时候，，然后保存就报错说不是json，，但是在线json里面就可以

### ISSUE THREAD

**Issue by wwg2017** [zyqwst/json-schema-editor-vue#44]
{
        "data": {       
                "c": [{                      
                        "Expires": "2019-08-03 14:46:24",
                        "Path": "/"        
                }]    
        }
}

就这个json保存不了，

**Comment by zyqwst** [comment]
我拷贝出来可以导入，http://json-schema.sviip.com/

**Comment by wwg2017** [comment]
> 我拷贝出来可以导入，http://json-schema.sviip.com/

我保存到这的时候已经去除了一些非法空格，，你要点击编辑 才能看到原始的，在这里复制出来
![image](https://user-images.githubusercontent.com/27998578/215659023-67b4f1ba-5a7c-42e4-bc2c-d53f33ee196f.png)
