### ISSUE TITLE
How to make possible nullable types?

### ISSUE THREAD

**Issue by tpoxa** [zyqwst/json-schema-editor-vue#45]
It would be great to have the ability to enable nullable type.
For example, the nullable object should look like this:

```JSON
{
  "properties": {},
  "type":["object",  "null"]
}
```

Thanks!

**Comment by zyqwst** [comment]
Thanks a lot for your suggestion, you can set required item to false
![image](https://user-images.githubusercontent.com/10893736/222654503-16817615-d2d7-4502-8133-14223ac76d6a.png)

**Comment by tpoxa** [comment]
Unfortunately, that is not the same. Required means the field must be presented and must be a string. Null will not pass the validation of such a scheme.
