### ISSUE TITLE
如何做到修改computed的值而不报错并继续运行的呢？

### ISSUE THREAD

**Issue by XianZhengquan** [zyqwst/json-schema-editor-vue#48]
我把v2.2.2的源码拉下来，进行拓展时，发现运行不了，当我进行修改的时候，就开始报错了
![image](https://github.com/zyqwst/json-schema-editor-vue/assets/46179450/2a449618-3582-4c8f-85e5-a95b934fe4fa)
<img width="867" alt="image" src="https://github.com/zyqwst/json-schema-editor-vue/assets/46179450/e29d19cf-8e6b-4dc5-a6fc-bd81cb26995b">

**Comment by zyqwst** [comment]
你是要改成element-ui吗？建议使用其他开源应用【https://github.com/giscafer/vue-json-schema-editor-visual】。
另外报错的原因是v-model变量是computed的原因
