### ISSUE TITLE
feat:  页面是否可以默认新增一个「默认值」的输入框

### ISSUE THREAD

**Issue by color-yi** [zyqwst/json-schema-editor-vue#51]
请问在页面可以默认新增一个「默认值」的属性吗？现在只能是在高级设置里面通过自定义属性增加 default 属性了

**Comment by zyqwst** [comment]
我准备做一个配置，可以在初始化时增加一些配置字段，比如你说的default。将会在2.3.0版本实现

**Comment by zyqwst** [comment]
2.3.0版本已实现此功能，请点击查看https://github.com/zyqwst/json-schema-editor-vue?tab=readme-ov-file#%E9%A2%9D%E5%A4%96%E9%85%8D%E7%BD%AE
